name: Deploy AMBA

on:
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

env:
  Location: "norwayeast"
  ManagementGroupPrefix: "demo-charles"

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    environment: deploy

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Az CLI Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Verify Authenticated Identity
        run: |
          az account show

      - name: Check Role Assignments
        run: |
          az role assignment list --assignee a68a7a78-da65-45f8-a416-edf62baa0a51 --scope /providers/Microsoft.Management/managementGroups/demo-charles --all

      - name: Validate ARM Template
        run: |
          az deployment mg validate --template-uri https://raw.githubusercontent.com/Azure/azure-monitor-baseline-alerts/main/patterns/alz/alzArm.json \
            --location ${{ env.Location }} \
            --management-group-id ${{ env.ManagementGroupPrefix }} \
            --parameters ./patterns/alz/alzArm.param.json

      - name: Deploy ARM Template
        run: |
          az deployment mg create --template-uri https://raw.githubusercontent.com/Azure/azure-monitor-baseline-alerts/main/patterns/alz/alzArm.json \
            --location ${{ env.Location }} \
            --management-group-id ${{ env.ManagementGroupPrefix }} \
            --parameters ./patterns/alz/alzArm.param.json
